apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender
  labels:
    app: sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sender
  template:
    metadata:
      labels:
        app: sender
    spec:
      containers:
      - name: server
        image: glebosotov/inno-tv-rabbitmq-sender:latest
        ports:
        - containerPort: 5672
        env:
          - name: HOST
            value: "10.102.201.79"
          - name: PORT
            value: "5672"
          - name: LOGIN
            value: "rabbit_user"
          - name: PASSWORD
            value: "rabbit_password"